site_name: My VDocs
site_description: Documentation technique — DHCP, NFS, AD, Cisco, et plus
site_author: Admin Réseau

theme:
  name: material
  language: fr
  font:
    text: Roboto
    code: "Fira Code"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer en mode sombre
      cards:
        background: "#e3f2fd"
        hover: "#bbdefb"
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode clair
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand: false
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.integrate
    - cards

markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: cisco
          class: cisco
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: yaml
          class: yaml
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: bash
          class: bash
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.snippets

plugins:
  - search:
      separator: '[\s-.]+'
      lang:
        - fr
        - en
plugins:
  - search
  - git-revision-date-localized:
      type: custom       
      locale: fr
      timezone: Europe/Paris
      fallback_to_build_date: false
      custom_format: "%d/%m/%Y"


nav:
  - Accueil: index.md
  - Notice:
      - DHCP :
          - Installation et configuration de base: Notice/DHCP/DHCP_base.md
          - Configuration VLAN: Notice/DHCP/DHCP_vlan.md
      - OSPF :
          - OSPF : Notice/OSPF/ospf.md
          - OSPFv3 : Notice/OSPF/ospfv3.md
      - NFS / SAMBA :
          - NFS: Notice/NFS_SAMBA/nfs.md
          - SAMBA: Notice/NFS_SAMBA/samba.md
      - Apache : Notice/apache.md
      - Proxy Squid: Notice/proxysquid.md
      - Active Directory:
          - Installation et configuration de base: Notice/Active Directory/AD_base.md
          - Utilisateurs et Groupes: Notice/Active Directory/AD_users.md
          - GPO: Notice/Active Directory/AD_GPO.md
  - Guide:
      - Commandes Switch/Routeur Cisco: Guide/commande_de_base_cisco.md
      - Commandes Switch Alcatel: Guide/commandes_alcatel.md
      - Git / Github : Guide/git_github.md
