site_name: My VDocs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: light-blue
    # Palette pour le mode clair
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    # Palette pour le mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair

markdown_extensions:
  - codehilite
  - fenced_code
  - tables
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Accueil: index.md
  - Notice:
      - DHCP : material/network
          - Installation et config de base : Notice/DHCP/DHCP_base.md
          - Config VLAN : Notice/DHCP/DHCP_vlan.md
      - NFS / SAMBA : material/folder-network
          - NFS : Notice/NFS_SAMBA/nfs.md
          - SAMBA : Notice/NFS_SAMBA/samba.md
      - APACHE : material/apache
          - Apache : Notice/apache.md
      - Proxy Squid : material/server-network
          - Proxy Squid : Notice/proxysquid.md
      - AD : material/microsoft
          - Installation et config de base : Notice/Active Directory/AD_base.md
          - Users et Groupe : Notice/Active Directory/AD_users.md
          - GPO : Notice/Active Directory/AD_GPO.md
  - Guide:
      - Commande Switch/Routeur Cisco : material/cisco
          - Commandes de base : Guide/commande_de_base_cisco.md
      - Commande Switch Alcatel : material/router
          - Commandes Alcatel : Guide/commandes_alcatel.md
