site_name: My VDocs

theme:
  name: material
  palette:
    # Palette pour le mode clair
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    # Palette pour le mode sombre
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair

markdown_extensions:
  - codehilite
  - fenced_code
  - tables
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Accueil: 
      - icon: material/home
        title: Accueil
        path: index.md
  - Notice:
      - icon: material/book-open-page-variant
        title: DHCP
        children:
          - icon: material/lan
            title: Installation et config de base
            path: Notice/DHCP/DHCP_base.md
          - icon: material/lan-connect
            title: Config VLAN
            path: Notice/DHCP/DHCP_vlan.md
      - icon: material/folder-network
        title: NFS / SAMBA
        children:
          - icon: material/nfs
            title: NFS
            path: Notice/NFS_SAMBA/nfs.md
          - icon: material/folder-multiple
            title: SAMBA
            path: Notice/NFS_SAMBA/samba.md
      - icon: material/web
        title: APACHE
        path: Notice/apache.md
      - icon: material/shield
        title: Proxy Squid
        path: Notice/proxysquid.md
      - icon: material/domain
        title: AD
        children:
          - icon: material/server
            title: Installation et config de base
            path: Notice/Active Directory/AD_base.md
          - icon: material/account-multiple
            title: Users et Groupe
            path: Notice/Active Directory/AD_users.md
          - icon: material/file-cog
            title: GPO
            path: Notice/Active Directory/AD_GPO.md
  - Guide:
      - icon: material/console
        title: Commande Switch/Routeur Cisco
        path: Guide/commande_de_base_cisco.md
      - icon: material/switch
        title: Commande Switch Alcatel
        path: Guide/commandes_alcatel.md