name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenchement sur la branche principale

permissions:
  contents: write  # Nécessaire pour publier sur gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          pip install pymdown-extensions

      - name: Deploy site
        run: mkdocs gh-deploy --force