name: Deploy to OVH SFTP

on:
  push:
    branches:
      - main # ou 'master' selon votre branche

jobs:
  web-deploy:
    name: Deploy Zensical Site
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      # On suppose que le dossier 'site/' est déjà généré

      - name: Sync files to OVH via pure SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './site/*'
          remote_path: '/www'
          sftp_only: true # CRUCIAL : Force le mode transfert uniquement, sans exécution SSH
