name: Documentation

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Zensical
        run: pip install zensical

      - name: Build Zensical site
        run: zensical build --clean

      # ---------------------------------------------------------
      # DÉPLOIEMENT CHEZ OVH (SFTP) - Chemin absolu corrigé
      # ---------------------------------------------------------
      - name: Deploy to OVH via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './site/*'
          remote_path: '/home/logovic/www/'
          sftp_only: true

      # ---------------------------------------------------------
      # DÉPLOIEMENT GITHUB PAGES
      # ---------------------------------------------------------
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
